version: '3.8'

services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"

  java-backend:
    build:
      context: ./mojo-api
    ports:
      - "8080:8080"
    depends_on:
      - flask-app
