name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Heroku Container Registry
      run: echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

    - name: Build and push Docker images
      run: |
        docker buildx build --platform linux/amd64 -t registry.heroku.com/<Revenue-Prediction>/web .
        docker push registry.heroku.com/<Revenue-Prediction>/web

    - name: Release to Heroku
      run: heroku container:release web --app <Revenue-Prediction>
